apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: newjeans-ingress
  annotations:
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "http://localhost:8080, http://localhost:5173, http://mafront.ildal.store, http://ma.ildal.store, http://msafront.ildal.store, http://msa.ildal.store, http://192.168.0.87:5173, http://192.168.0.17:8080"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, PUT, DELETE, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-headers: "*"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
spec:
  rules:
    - http:
        paths:
          - path: /schedule
            pathType: Prefix
            backend:
              service:
                name: calendar-service
                port:
                  number: 50002
          - path: /diary
            pathType: Prefix
            backend:
              service:
                name: calendar-service
                port:
                  number: 50002
          - path: /calendar-service
            pathType: Prefix
            backend:
              service:
                name: calendar-service
                port:
                  number: 50002
          - path: /friends-service
            pathType: Prefix
            backend:
              service:
                name: friends-service
                port:
                  number: 50003
          - path: /message
            pathType: Prefix
            backend:
              service:
                name: messages-service
                port:
                  number: 50004
          - path: /noti
            pathType: Prefix
            backend:
              service:
                name: notice-service
                port:
                  number: 50005
          - path: /user-service
            pathType: Prefix
            backend:
              service:
                name: users-service
                port:
                  number: 50001
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: users-service
                port:
                  number: 50001
          - path: /
            pathType: Prefix
            backend:
              service:
                name: friends-service
                port:
                  number: 50003

  ingressClassName: nginx
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ingress-nginx-controller
  namespace: ingress-nginx
data:
  enable-cors: "true"
  cors-allow-origin: "http://localhost:8080 http://localhost:5173 http://mafront.ildal.store http://ma.ildal.store http://msafront.ildal.store http://msa.ildal.store http://192.168.0.87:5173 http://192.168.0.17:8080"
  cors-allow-methods: "GET, POST, PUT, DELETE, OPTIONS"
  cors-allow-headers: "*"
  cors-allow-credentials: "true"