server:
  port: 50002

spring:
  application:
    name: calendarService
  sql:
    init:
      mode: never

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    #    url: jdbc:mariadb://localhost:3306/newjeans?serverTimezone=Asia/Seoul
#    url: jdbc:mariadb://192.168.0.41:30002/newjeans?serverTimezone=Asia/Seoul
#    url: jdbc:mariadb://192.168.0.113:30002/newjeans?serverTimezone=Asia/Seoul
    url: jdbc:mariadb://192.168.0.68:30002/newjeans?serverTimezone=Asia/Seoul

    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate.format_sql: true
    show-sql: true
    open-in-view: false

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      file-size-threshold: 0
      enabled: true

# 로컬 이미지 저장 루트
#ImgLocation: "D:/images"
#ProfileImgLocation: "D:/profileImages"
#uploadPath: "file:///D:/images/"
#profileUploadPath: "file:///D:/profileImages/"

# 서버 이미지 저장 루트
ImgLocation: "/app/images"
ProfileImgLocation: "/app/profileImages"
uploadPath: "file:///D:/images/"
profileUploadPath: "file:///D:/profileImages/"

# MacBook 데스크톱 이미지 저장 경로 설정
#ImgLocation: "/Users/pc/Downloads/images"
#ProfileImgLocation: "/Users/pc/Downloads/profileImages"
#uploadPath: "file:///Users/pc/Downloads/images/"
#profileUploadPath: "file:///Users/pc/Downloads/profileImages/"

user-service-url: http://localhost:50001
friend-service-url: http://localhost:50003
