server:
  port: 50002

spring:
  application:
    name: calendarService
  sql:
    init:
      mode: never

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
#        url: jdbc:mariadb://localhost:3306/newjeans?serverTimezone=Asia/Seoul
#    url: jdbc:mariadb://192.168.0.41:30002/newjeans?serverTimezone=Asia/Seoul
#    url: jdbc:mariadb://192.168.0.113:30002/calendar?serverTimezone=Asia/Seoul
#    url: jdbc:mariadb://192.168.0.113:3333/calendar?serverTimezone=Asia/Seoul
#    url: jdbc:mariadb://192.168.0.83:30002/newjeans?serverTimezone=Asia/Seoul
#    url: jdbc:mariadb://192.168.0.83:3307/newjeans?serverTimezone=Asia/Seoul

    # 쿠버네티스 로컬 주소
    url: jdbc:mariadb://192.168.0.17:30002/calendar?serverTimezone=Asia/Seoul

    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
    show-sql: true
    open-in-view: false

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      file-size-threshold: 0
      enabled: true
  jwt:
    secret: asdklfjdaslkfj2iofj308f230f203f20f03ffjf2jf0
    token-valid-time: 86400000
    refresh-token-valid-time: 604800000

kakao:
  client-id: 2515f45fc0d9a50bfeee4e2db7c37005
  client-secret: VTtYUbpcA51R3KZaRhcB4cWDTqL40akQ
  redirect-uri: "http://localhost:5173/kakaologin"

# 로컬 이미지 저장 루트
#ImgLocation: "D:/images"
#ProfileImgLocation: "D:/profileImages"
#uploadPath: "file:///D:/images/"
#profileUploadPath: "file:///D:/profileImages/"

# 서버 이미지 저장 루트
ImgLocation: "/app/images"
ProfileImgLocation: "/app/profileImages"
uploadPath: "file:///D:/images/"
profileUploadPath: "file:///D:/profileImages/"

# MacBook 데스크톱 이미지 저장 경로 설정
#ImgLocation: "/Users/pc/Downloads/images"
#ProfileImgLocation: "/Users/pc/Downloads/profileImages"
#uploadPath: "file:///Users/pc/Downloads/images/"
#profileUploadPath: "file:///Users/pc/Downloads/profileImages/"

#users-service-url: http://192.168.0.17:50001
#calendar-service-url: http://192.168.0.17:50002
#friends-service-url: http://192.168.0.17:50003
#messages-service-url: http://192.168.0.17:50004
#notice-service-url: http://192.168.0.17:50005

users-service-url: http://localhost:50001
calendar-service-url: http://localhost:50002
friends-service-url: http://localhost:50003
messages-service-url: http://localhost:50004
notice-service-url: http://localhost:50005

cors:
  allowed-origins: http://localhost:8080, http://localhost:5173, http://mafront.ildal.store, http://ma.ildal.store, http://msafront.ildal.store, http://msa.ildal.store, http://192.168.0.87:5173, http://192.168.0.17:8080