apiVersion: v1
kind: ConfigMap
metadata:
  name: nj-k8s-configmap
data:
  access_token_expiration_time: "86400" # 하루
  refresh_token_expiration_time: "2592000" # 한 달
  token_secret: "abcdefghijklmnopqrstuvwxyz01234567890"
  bootstrap-servers: "172.30.1.58:9092"
  user-service-port: "50001"
  calendar-service-port: "50002"
  friend-service-port: "50003"
  spring-datasource-url-user: "jdbc:mariadb://mariadb-userNJ:3333/msa"
  spring-datasource-url-friend: "jdbc:mariadb://mariadb-friendNJ:3333/msa"
  spring-datasource-url-calendar: "jdbc:mariadb://mariadb-calendarNJ:3333/msa"
  spring-datasource-username: "root"
