apiVersion: v1
kind: ConfigMap
metadata:
  name: nj-k8s-configmap
data:
  access_token_expiration_time: "86400" # 하루
  refresh_token_expiration_time: "2592000" # 한 달
  token_secret: "abcdefghijklmnopqrstuvwxyz01234567890"
  bootstrap-servers: "172.30.1.58:9092"

  users-service-port: "50001"
  calendar-service-port: "50002"
  friends-service-port: "50003"
  messages-service-port: "50004"
  notice-service-port: "50005"

  spring-datasource-url-users: "jdbc:mariadb://mariadb-users:3306/users"
  spring-datasource-url-friends: "jdbc:mariadb://mariadb-friends:3306/friends"
  spring-datasource-url-calendar: "jdbc:mariadb://mariadb-calendar:3306/calendar"
  spring-datasource-url-notice: "jdbc:mariadb://mariadb-notice:3306/notice"
  spring-datasource-url-messages: "jdbc:mariadb://mariadb-messages:3306/messages"

  spring-datasource-username: "root"
